-- PostgreSQL migration helper
DO $$ BEGIN
    ALTER TYPE status ADD VALUE IF NOT EXISTS 'AWAITING_APPROVAL';
    ALTER TYPE status ADD VALUE IF NOT EXISTS 'APPROVED';
    ALTER TYPE status ADD VALUE IF NOT EXISTS 'CREDIT_USED';
    ALTER TYPE status ADD VALUE IF NOT EXISTS 'RESOLVED';
    ALTER TYPE status ADD VALUE IF NOT EXISTS 'CLOSED';
EXCEPTION WHEN others THEN NULL; END $$;

ALTER TABLE email_items ADD COLUMN IF NOT EXISTS assignee VARCHAR(255);
ALTER TABLE email_items ADD COLUMN IF NOT EXISTS tags VARCHAR(512);

CREATE TABLE IF NOT EXISTS activity_logs (
    id SERIAL PRIMARY KEY,
    email_item_id INTEGER REFERENCES email_items(id) ON DELETE CASCADE,
    at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    actor VARCHAR(255) NOT NULL,
    action VARCHAR(255) NOT NULL,
    details TEXT
);
CREATE INDEX IF NOT EXISTS ix_activity_logs_email_item_id ON activity_logs(email_item_id);
CREATE INDEX IF NOT EXISTS ix_activity_logs_at ON activity_logs(at);

ALTER TABLE photos ADD COLUMN IF NOT EXISTS sha256 VARCHAR(64);
